anna_project/anna/urls.py
from django.conf.urls import url

from . import views

app_name = 'anna'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^results/$', views.searchResults, name='results'),
]

anna_project/anna_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('anna.urls')),
    url(r'^admin/', admin.site.urls),
]

anna_project/anna/models.py
from django.db import models


class Paragraph(models.Model):
    text = models.TextField()

    def __str__(self):
        return "Paragraph " + str(self.id)


class Word(models.Model):
    word = models.CharField(max_length=100, db_index=True, unique=True)
    paragraphs = models.ManyToManyField(Paragraph)

    def __str__(self):
        return self.word

anna_project/anna/forms.py
from django import forms


class QueryForm(forms.Form):
    query = forms.CharField(label='Search', max_length=2000)

anna_project/anna/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse
from .models import Paragraph, Word
from .forms import QueryForm

# parser imports
from .lexer import anna_lexer
from .parser import parse


def index(request):
    """
    view for the index page of the apps
    """
    form = QueryForm()
    context = {'form': form}
    return render(request, 'anna/index.html', context)


def searchResults(request):
    """
    view for the results page
    """
    context = {}
    query = request.GET.get('query')
    print('User query: {q}'.format(q=query))
    context['query'] = query

    form = QueryForm(request.GET)
    context['form'] = form

    if len(query) > 0:
        # search in db
        try:
            paragraphs = None

            # parse the query
            tokens = anna_lexer(query)
            print('Query tokens: {t}'.format(t=tokens))
            parse_result = parse(tokens)

            if not parse_result:
                print('Parsing error')
                context['error'] = 'Parsing error'
            else:
                # get AST and print to console
                ast = parse_result.value
                print('AST: {ast}'.format(ast=ast))

                # get list from evaluated AST for paginator
                res = [i for i in ast.eval()]
                context['num_paragraphs'] = len(res)
                paginator = Paginator(res, 10)
                page = request.GET.get('page')
                try:
                    paragraphs = paginator.page(page)
                except PageNotAnInteger:
                    # If page is not an integer, deliver first page
                    paragraphs = paginator.page(1)
                except EmptyPage:
                    # If page is out of range, deliver last page of results
                    paragraphs = paginator.page(paginator.num_pages)
            context['paragraphs'] = paragraphs
        except Word.DoesNotExist:
            print('Err: obj Word does not exist')
    return render(request, 'anna/results.html', context)

anna_project/anna/templates/anna/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Anna Karenina</title>
        <meta name="author" content="Sergey Nikiforov" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'anna/css/foundation.min.css' %}" />
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block main %}
        {% endblock main %}
        <script src="{% static 'anna/js/vendor/jquery.min.js' %}"></script>
        <script src="{% static 'anna/js/foundation.min.js' %}"></script>
    </body>
</html>

anna_project/anna/templates/anna/index.html
{% extends "anna/base.html" %}
{% load staticfiles %}
{% block main %}
    <div class="callout large secondary">
        <div class="row column text-center">
            <h1><strong>Anna Karenina</strong></h1>
            <h3 class="subheader">by Leo Tolstoy</h3>
        </div>
    </div>
    <div class="row medium-8 large-7 columns">
        <form action="{% url 'anna:results' %}" method="get" accept-charset="utf-8">
            <div class="input-group">
                <span class="input-group-label">Query:</span>
                <input id="query" type="text" class="input-group-field" name="query">
                <div class="input-group-button">
                    <input type="submit" class="button" value="search">
                </div>
            </div>
        </form>
    </div>
{% endblock main %}

anna_project/anna/templates/anna/results.html
{% extends "anna/base.html" %}
{% load staticfiles %}
{% block main %}
    <div class="callout {% if paragraphs %}success{% else %}alert{% endif %} primary">
        <div class="row column text-center">
            <h1><a href="{% url 'anna:index' %}"><strong>Anna Karenina</strong></a></h1>
        </div>
    </div>
    <div class="row medium-8 large-7 columns">
        <form action="{% url 'anna:results' %}" method="get" accept-charset="utf-8">
            <div class="input-group">
                <span class="input-group-label">Query:</span>
                <input id="query" type="text" class="input-group-field" name="query" value="{{ query }}">
                <div class="input-group-button">
                    <input type="submit" class="button" value="search">
                </div>
            </div>
        </form>
    </div>
    <div class="row medium-10 large-9 columns">
        {% if error %}
            <h6 class="subheader">{{ error }}</h6>
        {% endif %}
        {% if not query %}
            <h6 class="subheader">Empty query</h6>
        {% endif %}
        {% if num_paragraphs == 0 %}
            <h6 class="subheader">No paragraphs matching your query</h6>
        {% endif %}
        {% if num_paragraphs %}
            {% if num_paragraphs == 1 %}
                <h6 class="subheader">{{ num_paragraphs }} paragraph</h6>
            {% else %}
                <h6 class="subheader">{{ num_paragraphs }} paragraphs</h6>
            {% endif %}
        {% endif %}
        <hr>
        {% if paragraphs %}
            <ul class="pagination" role="navigation" aria-label="Pagination">
                {% if paragraphs.has_previous %}
                    <li class="pagination-previous"><a href="?query={{ query }}&page={{ paragraphs.previous_page_number }}">prev</a></li>
                {% endif %}
                <span class="current">
                    Page {{ paragraphs.number }} of {{ paragraphs.paginator.num_pages }}
                </span>
                {% if paragraphs.has_next %}
                    <li class="pagination-next"><a href="?query={{ query }}&page={{ paragraphs.next_page_number }}" aria-label="Next page">next</a></li>
                {% endif %}
            </ul>
            <ul class="no-bullet">
                {% for paragraph in paragraphs %}
                    <li><p>{{ paragraph.text }}</p></li>
                {% endfor %}
            </ul>
            <ul class="pagination" role="navigation" aria-label="Pagination">
                {% if paragraphs.has_previous %}
                    <li class="pagination-previous"><a href="?query={{ query }}&page={{ paragraphs.previous_page_number }}">prev</a></li>
                {% endif %}
                <span class="current">
                    Page {{ paragraphs.number }} of {{ paragraphs.paginator.num_pages }}
                </span>
                {% if paragraphs.has_next %}
                    <li class="pagination-next"><a href="?query={{ query }}&page={{ paragraphs.next_page_number }}" aria-label="Next page">next</a></li>
                {% endif %}
            </ul>
            <hr>
        {% else %}
            <p>No paragraphs available</p>
        {% endif %}
    </div>
{% endblock main %}